version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: var404
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cryptobot
    ports:
      - '5433:5432'
