[variables]
    NODE_VERSION = "20"

[phases.setup]
    nixPkgs = ["nodejs", "openssl"]

[phases.build]
    cmds = ["npm ci", "npm run build"]

[phases.start]
    cmd = "npx prisma migrate deploy && npm run start:prod"
