[variables]
    NODE_VERSION = "20"

[phases.setup]
    nixPkgs = ["nodejs", "openssl", "pnpm"]

[phases.build]
    cmds = ["pnpm install", "pnpm run build"]

[phases.start]
    cmd = "npx prisma db push --accept-data-loss && pnpm run start:prod"
