[variables]
    NODE_VERSION = "20"

[phases.setup]
    nixPkgs = ["nodejs", "openssl"]
    cmds = ["npm install -g pnpm"]

[phases.build]
    cmds = ["pnpm install --frozen-lockfile", "pnpm run build"]

[phases.start]
    cmd = "npx prisma migrate deploy && pnpm run start:prod"
